<%@ Page Title="addNewAdmin" Language="C#" MasterPageFile="~/AdminMaster.master" AutoEventWireup="true"
    CodeFile="addNewAdmin.aspx.cs" Inherits="newAdmin" %>

<asp:Content ID="HeaderContent" runat="server" ContentPlaceHolderID="HeadContent">
</asp:Content>
<asp:Content ID="BodyContent" runat="server" ContentPlaceHolderID="MainContent">
    <div class="tab-content" id="tab2" style= "padding-left: 20px;">
        <form action="#" method="post">
            <p style="line-height: 30px">
                <asp:Label ID="LblUser" runat="server" Width="80px">User ID: </asp:Label>
                <asp:TextBox ID="username"  MaxLength=20 Height="20" runat="server"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" 
                    ControlToValidate="username" ErrorMessage="*Required"></asp:RequiredFieldValidator>
                <asp:RegularExpressionValidator ID="checkuname" runat="server" ErrorMessage="Incorrect, must be between 4-10 bits letters or numbers ." ControlToValidate="username" ValidationExpression="[a-zA-Z0-9]{4,10}" />
                <br />

                <asp:Label ID="Label1" runat="server" Width="80px">Password: </asp:Label>
                <asp:TextBox ID="right"  TextMode="Password"  MaxLength=20 Height="20" runat="server"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator2" ControlToValidate="right" runat="server" ErrorMessage="Required Field">*Required</asp:RequiredFieldValidator> 
                <asp:RegularExpressionValidator ID="RegularExpressionValidator4" runat="server" ErrorMessage="Invalid, must be between 4-10 bits letters or numbers ." ControlToValidate="right" ValidationExpression="[a-zA-Z0-9]{4,10}" />
                <br />

                <asp:Label ID="Label2" runat="server" Width="80px">Email: </asp:Label>
                <asp:TextBox ID="email" MaxLength = "50"  width="300" Height="20" Text="" runat="server"  Font-Size="12"></asp:TextBox>
			                        <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ControlToValidate="email" ErrorMessage="Required Field" Display="Dynamic">*Required</asp:RequiredFieldValidator>
                                    <asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" ValidationExpression="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*" 
                                        ErrorMessage="RegularExpressionValidator" BorderStyle="None" ControlToValidate="email">Not an Email format</asp:RegularExpressionValidator>                                                   
                <br />

            </p> 
                              
                <div>
                    &nbsp;&nbsp;&nbsp;&nbsp; 
		            <asp:Button ID="Button1" class="button"  Visible="true" Text="Add admin" runat="server" onclick="BtnSubmit_Click1" /> 
                    &nbsp;&nbsp;&nbsp;&nbsp; 
                    <asp:Button ID="Button2" class="button"  Visible="true" Text="Clear" runat="server" OnClientClick="this.form.reset();return false;" />     
                     &nbsp;&nbsp;&nbsp;&nbsp;       
                    <asp:CheckBox ID="checkMode" AutoPostBack="true" OnCheckedChanged="checkMode_CheckedChanged" runat="server" TextAlign=Right Checked="false"/>
                    <asp:Label ID="Label3" runat="server">Edit Mode </asp:Label>
                </div>  
                                
            <div class="clear"></div>
            <!-- End .clear -->
        </form>
    </div>
    <!-- End #tab2 -->
 <asp:Panel ID="PnlTable" runat="server">
    <asp:GridView ID="admin" runat="server"
           AllowSorting="True" AutoGenerateColumns="False" ShowFooter="True" PageSize="20"
           AllowPaging="True" OnPageIndexChanging="admin_PageIndexChanging" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" DataKeyNames="JID"
            OnRowCancelingEdit="admin_RowCancelingEdit" OnRowDeleting="admin_RowDeleting" OnRowUpdating="admin_RowUpdating" OnRowEditing="admin_RowEditing">
     
        <Columns>
           <asp:templatefield headertext="User ID"><itemtemplate><%#Eval("JID") %> </itemtemplate>
           </asp:templatefield>

           <asp:templatefield headertext="Password"><itemtemplate><%#Eval("pwd") %> </itemtemplate>
           <edititemtemplate>
           <asp:textbox id="textbox1" runat='server' text='<%#Eval("pwd") %>'></asp:textbox>
           </edititemtemplate>
            </asp:templatefield>

            <asp:templatefield headertext="Email"><itemtemplate><%#Eval("Email") %> </itemtemplate>
           <edititemtemplate>
           <asp:textbox id="textbox2" runat='server' Text='<%#Eval("Email") %>'></asp:textbox>
           </edititemtemplate>
            </asp:templatefield>
         </Columns>
                    <PagerTemplate>
                <table align="right" bgcolor="#e9e9e9" width="100%">
                    <tr>
                        <td style="text-align: right">
                            Page <b><asp:Label ID="lblPageIndex" runat="server" Text="<%#((GridView)Container.Parent.Parent).PageIndex + 1 %>"></asp:Label></b>
                            of <b><asp:Label ID="lblPageCount" runat="server" Text="<%# ((GridView)Container.Parent.Parent).PageCount %>"></asp:Label></b>
                            <asp:LinkButton ID="btnFirst" runat="server" CausesValidation="False" CommandArgument="First"
                                CommandName="Page" Enabled="<%# ((GridView)Container.NamingContainer).PageIndex != 0 %>"
                                Text="First  "></asp:LinkButton>
                            <asp:LinkButton ID="btnPrev" runat="server" CausesValidation="False" CommandArgument="Prev"
                                CommandName="Page" Enabled=" <%# ((GridView)Container.NamingContainer).PageIndex != 0 %>"
                                Text="<< Previous  "></asp:LinkButton>
                            <asp:LinkButton ID="btnNext" runat="server" CausesValidation="False" CommandArgument="Next"
                                CommandName="Page" Enabled=" <%# ((GridView)Container.NamingContainer).PageIndex != ((GridView)Container.NamingContainer).PageCount - 1 %>"
                                Text="  Next >>"></asp:LinkButton>
                            <asp:LinkButton ID="btnLast" runat="server" CausesValidation="False" CommandArgument="Last"
                                CommandName="Page" Enabled=" <%# ((GridView)Container.NamingContainer).PageIndex != ((GridView)Container.NamingContainer).PageCount - 1 %>"
                                Text="  Last"></asp:LinkButton>
                            <asp:TextBox ID="txtNewPageIndex" runat="server" Text="<%# ((GridView)Container.Parent.Parent).PageIndex + 1%>"
                                Width="20px"></asp:TextBox>
                            <asp:LinkButton ID="btnGo" runat="server" CausesValidation="false" CommandArgument="-1"
                                CommandName="Page" Text="GO"></asp:LinkButton>
                        </td>
                    </tr>
                </table>
            </PagerTemplate>

    </asp:GridView>
     </asp:Panel>
</asp:Content>
