/* Copyright by Indiana University Purdue University Indianapolis
 * School of Computer & Informatic Science
 * Dian Wen & Rui Wang
 * 2013 Jan-May
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.IO;
using System.Text;
using System.Web.Configuration;

public partial class _Default : System.Web.UI.Page
{
    static string cs = WebConfigurationManager.ConnectionStrings["localConnection"].ConnectionString;
    SqlConnection con = new SqlConnection(cs);

    protected void Page_Load(object sender, EventArgs e)
    {
        if (!IsPostBack)
        {
            getAllAssignment();
        }

    }

    // Search assignments
    protected void getAssignment(object sender, EventArgs e)
    {
        string searchBy = SearchArea.SelectedValue;
        string value = SearchTxt.Text;
        if (searchBy == "JID")
        {
            string sql = "select * from AssignmentList where  JudgeID = '" + value + "'";
            bind(sql);
        }
        else if (searchBy == "PID")
        {
            string sql = "select * from AssignmentList where ProjectID ='" + value + "'";
            bind(sql);
        }
        else if (searchBy == "AID")
        {
            string sql = "select * from AssignmentList where AID ='" + value + "'";
            bind(sql);
        }
       
    }

    // Get alll the assignments
    protected void getAllAssignment()
    {
        string sql = "select * from AssignmentList";
        bind(sql);
    }

    protected void bind(string sql)
    {
        SqlCommand cmd = new SqlCommand(sql, con);
        try
        {
            con.Open();
            SqlDataReader reader = cmd.ExecuteReader();
            DataTable dt = new DataTable();
            ViewState["dspage"] = dt;
            dt.Load(reader);
            Grid1.DataSource = dt;
            Grid1.DataBind();

        }
        finally
        {
            con.Close();
        }
    }

    protected void PageIndexChanging(object sender, GridViewPageEventArgs e)
    {
        GridView theGrid = sender as GridView;  // refer to the GridView
        int newPageIndex = 0;

        if (-2 == e.NewPageIndex)
        { // when click the "GO" Button
            TextBox txtNewPageIndex = null;
            GridViewRow pagerRow = theGrid.BottomPagerRow;

            if (null != pagerRow)
            {
                txtNewPageIndex = pagerRow.FindControl("txtNewPageIndex") as TextBox;   // refer to the TextBox with the NewPageIndex value
            }

            if (null != txtNewPageIndex)
            {
                newPageIndex = int.Parse(txtNewPageIndex.Text) - 1; // get the NewPageIndex
            }
        }
        else
        {  // when click the first, last, previous and next Button
            newPageIndex = e.NewPageIndex;
        }

        // check to prevent form the NewPageIndex out of the range
        newPageIndex = newPageIndex < 0 ? 0 : newPageIndex;
        newPageIndex = newPageIndex >= theGrid.PageCount ? theGrid.PageCount - 1 : newPageIndex;

        // specify the NewPageIndex
        theGrid.PageIndex = newPageIndex;
        getAllAssignment();

        // rebind the control
        // in this case of retrieving the data using the xxxDataSoucr control,
        // just do nothing, because the asp.net engine binds the data automatically
    }

    protected void Grid1_RowDeleting(object sender, GridViewDeleteEventArgs e)
    {
        string aid = Grid1.DataKeys[e.RowIndex].Values["AID"].ToString();

        string period = Grid1.DataKeys[e.RowIndex].Values["periodID"].ToString(); ;
        string jid = Grid1.DataKeys[e.RowIndex].Values["JudgeID"].ToString(); ;
        string pid = Grid1.DataKeys[e.RowIndex].Values["ProjectID"].ToString(); ;

        string sql1 = "delete from Assignment where aid='" + aid + "'";
        string sql2 = "insert into Availability values ('"+jid+"','"+period+"')";
        string sql3 = "insert into ProjectAvailability values ('" + pid + "','" + period + "')";
        string sql4 = "update Project set Time = Time - 1 where PID = " + pid;
        string sql = sql1 + ";" + sql2 + ";" + sql3 + ";" + sql4;

        con.Open();
        SqlCommand cmd = new SqlCommand(sql, con);
        int result = cmd.ExecuteNonQuery();
        con.Close();
        getAllAssignment();
        AdminMaster master = (AdminMaster)Page.Master;
        master.AlertSuccess("Delete successfully");
    }

    // Print page function
    protected void PrintAllPages(object sender, EventArgs e)
    {

        GridView printable = new GridView();
        printable.AutoGenerateDeleteButton = false;
        printable.AutoGenerateEditButton = false;
        printable.AllowPaging = false;
        printable.DataSource = (DataTable)ViewState["dspage"];
        printable.DataBind();

        StringWriter sw = new StringWriter();
        HtmlTextWriter hw = new HtmlTextWriter(sw);

        printable.RenderControl(hw);

        string gridHTML = sw.ToString().Replace("\"", "'").Replace(System.Environment.NewLine, "");
        StringBuilder sb = new StringBuilder();
        sb.Append("<script type = 'text/javascript'>");
        sb.Append("window.onload = new function(){");
        sb.Append("var printWin = window.open('', '', 'left=0");
        sb.Append(",top=0,width=1000,height=600,status=0');");
        sb.Append("printWin.document.write(\"");
        sb.Append(gridHTML);
        sb.Append("\");");
        sb.Append("printWin.document.close();");
        sb.Append("printWin.focus();");
        sb.Append("printWin.print();");
        sb.Append("printWin.close();};");
        sb.Append("</script>");

        ClientScript.RegisterStartupScript(this.GetType(), "GridPrint", sb.ToString());
    }

    public override void VerifyRenderingInServerForm(Control control)
    {
        return;
    }
}